rcate-FinancialPortal/Models/Code First/Budget.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace rcate_FinancialPortal.Models.Code_First
{
    public class Budget
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        [Required]
        public int CategoryId { get; set; }
        public string OwnerId { get; set; }
        public int? HouseHoldId { get; set; }
        
        public virtual BudgetCategory Category { get; set; }
        public virtual ApplicationUser Owner { get; set; }
        public virtual HouseHold HouseHold { get; set; }
    }
}

rcate-FinancialPortal/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using rcate_FinancialPortal.Models;
using rcate_FinancialPortal.Models.Code_First;
using Microsoft.AspNet.Identity;

namespace rcate_FinancialPortal.Controllers
{
    [Authorize]
    public class BudgetsController : Universal
    {

        // GET: Budgets
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            var budgets = db.Budget.Where(b => b.HouseHoldId == user.HouseHoldId);
            return View(budgets.ToList());
        }

        // GET: Budgets/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Budget budget = db.Budget.Find(id);
        //    if (budget == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(budget);
        //}

        // GET: Budgets/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.BudgetCategory, "Id", "Name");
            return View();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,CategoryId,OwnerId,Amount,HouseHoldId")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());

                budget.HouseHoldId = user.HouseHold.Id;
                budget.OwnerId = user.Id;

                db.Budget.Add(budget);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.BudgetCategory, "Id", "Name", budget.CategoryId);
            return View(budget);
        }

        // GET: Budgets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budget.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.BudgetCategory, "Id", "Name", budget.CategoryId);
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FirstName", budget.OwnerId);
            return View(budget);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,CategoryId,OwnerId,Amount,HouseHoldId")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                db.Entry(budget).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.BudgetCategory, "Id", "Name", budget.CategoryId);
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FirstName", budget.OwnerId);
            return View(budget);
        }

        // GET: Budgets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budget.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Budget budget = db.Budget.Find(id);
            db.Budget.Remove(budget);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

rcate-FinancialPortal/Views/Budgets/Create.cshtml
@model rcate_FinancialPortal.Models.Code_First.Budget

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Budget</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

rcate-FinancialPortal/Views/Budgets/Delete.cshtml
@model rcate_FinancialPortal.Models.Code_First.Budget

@{
    ViewBag.Title = "Delete";
}

<h2>
    <b>Are you sure you want to delete this Budget: "<span style="color:red">@Model.Name</span>"?</b></h2>
<div>
    <hr />
    <div class="panel panel-default">
        <div class="panel-heading"></div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Amount
                    </th>
                </tr>

                    <tr>
                        <td>
                            @Html.DisplayFor(Model => Model.Name)
                        </td>
                        <td>
                            @if (Model.Description == null)
                            {
                                <i>No Description</i>
                            }
                            else
                            {
                                @Html.DisplayFor(Model => Model.Description)
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(Model => Model.Category.Name)
                        </td>
                        <td>
                            @string.Format("{0:C}", Model.Amount)
                        </td>
                    </tr>

            </table>
        </div>
        <div class="panel-footer">
        </div>
    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <br />
            <br />
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

rcate-FinancialPortal/Views/Budgets/Details.cshtml
@model rcate_FinancialPortal.Models.Code_First.Budget

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Budget</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Budget Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <br />

        <dt>
            Category
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <br />

        <dt>
            Amount
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")

    <br />

    <a class="btn btn-danger" href="@Url.Action("Delete", "Budgets", new { id = Model.Id })">Delete</a>
</p>

rcate-FinancialPortal/Views/Budgets/Edit.cshtml
@model rcate_FinancialPortal.Models.Code_First.Budget

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">
    <b>Edit Budget</b>
</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.OwnerId)
        @Html.HiddenFor(model => model.HouseHoldId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" style="background-color:orange;color:white" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

rcate-FinancialPortal/Views/Budgets/Index.cshtml
@model IEnumerable<rcate_FinancialPortal.Models.Code_First.Budget>

@{
    ViewBag.Title = "Index";
}

<h2><b>Budgets</b></h2>

<p>
    <a class="btn btn-warning pull-right" href="@Url.Action("Create", "Budgets")">Create New Budget</a>
</p>

<br />
<br />

<div class="panel panel-default">
    <div class="panel-heading">
        <center>
            <h4>
                <b>Budgets</b>
            </h4>
        </center>
    </div>
    <div class="panel-body">
        @if (Model.Count() == 0)
        {
            <h6><b>You have no transactions.</b></h6>
        }
        else
        {
            <table class="table">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Amount
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @if (item.Description == null)
                            {
                                <i>No Description</i>
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => item.Description)
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Category.Name)
                        </td>
                        <td>
                            @string.Format("{0:C}", item.Amount)
                        </td>
                        <td>
                            <a style="color:black" title="Edit" href="@Url.Action("Edit", "Budgets", new { id = item.Id })"><span class="fa fa-pencil"></span></a>
                            &nbsp;
                            <a style="color:red;margin-left:3px" title="Delete" href="@Url.Action("Delete", "Budgets", new { id = item.Id })"><span class="fa fa-trash-o"></span></a>
                        </td>
                    </tr>
                }

            </table>
        }

    </div>
    <div class="panel-footer">
    </div>
</div>