rcate-FinancialPortal/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using rcate_FinancialPortal.Models;
using rcate_FinancialPortal.Models.Code_First;
using Microsoft.AspNet.Identity;

namespace rcate_FinancialPortal.Controllers
{
    [Authorize]

    public class TransactionsController : Universal
    {

        // GET: Transactions
        public ActionResult Index(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            var transaction = user.HouseHold.Accounts.SelectMany(t => t.Transactions);
            return View(transaction.OrderByDescending(t => t.Created).ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            Accounts account = db.Accounts.Find(id);
            Transaction transaction = db.Transaction.Find(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (transaction == null)
            {
                return HttpNotFound();
            }

            return View(transaction);
        }

        // GET: Transactions/Create
        public ActionResult Create(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var account = db.Accounts.Find(id);

            ViewBag.CategoryId = new SelectList(db.TransactionCategory, "Id", "Name");
            ViewBag.AccountsId = new SelectList(db.Accounts.Where(a => a.HouseHoldId == user.HouseHoldId), "Id", "Name");
            ViewBag.BudgetId = new SelectList(db.Budget.Where(b => b.HouseHoldId == user.HouseHoldId), "Id", "Name");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Amount,Created,ReconciledAmount,Reconciled,AuthorId,CategoryId,AccountsId,BudgetId,ExpenseId,HouseHoldId")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());
                Accounts accounts = db.Accounts.Find(transaction.AccountsId);

                transaction.AuthorId = user.Id;
                transaction.Created = DateTime.Now;
                transaction.HouseHoldId = user.HouseHold.Id;
                transaction.Void = false;

                if (transaction.CategoryId == 2 && transaction.Void == false)
                {
                    decimal transAmt = transaction.Amount * -1;
                    accounts.Balance = accounts.Balance + transAmt;
                }
                if (transaction.CategoryId == 1 && transaction.Void == false)
                {
                    accounts.Balance = accounts.Balance + transaction.Amount;
                }

                db.Transaction.Add(transaction);
                db.Entry(accounts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var members = db.HouseHold.SelectMany(m => m.Members).ToList();

            ViewBag.AuthorId = new SelectList(members, "Id", "FullName", transaction.AuthorId);
            ViewBag.CategoryId = new SelectList(db.TransactionCategory, "Id", "Name", transaction.CategoryId);
            ViewBag.AccountsId = new SelectList(db.Accounts, "Id", "Name", transaction.AccountsId);
            //ViewBag.ExpenseId = new SelectList(db.Expense, "Id", "Name", transaction.ExpenseId);
            ViewBag.BudgetId = new SelectList(db.Budget, "Id", "Name", transaction.BudgetId);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transaction.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", transaction.AuthorId);
            ViewBag.CategoryId = new SelectList(db.TransactionCategory, "Id", "Name", transaction.CategoryId);
            ViewBag.AccountsId = new SelectList(db.Accounts, "Id", "Name");
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Amount,Created,ReconciledAmount,Reconciled,AuthorId,CategoryId,AccountsId,BudgetId,ExpenseId,HouseHoldId")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                Accounts accounts = db.Accounts.Find(transaction.AccountsId);

                if (transaction.CategoryId == 2 && transaction.Void == false)
                {
                    decimal transAmt = transaction.Amount * -1;
                    accounts.Balance = accounts.Balance + transAmt;
                }
                if (transaction.CategoryId == 1 && transaction.Void == false)
                {
                    accounts.Balance = accounts.Balance + transaction.Amount;
                }

                db.Entry(accounts).State = EntityState.Modified;
                db.Entry(transaction).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", transaction.AuthorId);
            ViewBag.CategoryId = new SelectList(db.TransactionCategory, "Id", "Name", transaction.CategoryId);
            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Name");
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transaction.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transaction.Find(id);
            db.Transaction.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Transaction/Void
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VoidTransaction(int? id)
        {
            Transaction transaction = db.Transaction.Find(id);
            transaction.Void = true;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Transaction/Un-Void
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UnVoidTransaction(int? id)
        {
            Transaction transaction = db.Transaction.Find(id);
            transaction.Void = false;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

rcate-FinancialPortal/Views/Transactions/Create.cshtml
@model rcate_FinancialPortal.Models.Code_First.Transaction

@{
    ViewBag.Title = "Create";
}

<center>
    <h2>
        <b>Create Transaction</b>
    </h2>
</center>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*<div class="row">
            <div class="form-group">
                @Html.LabelFor(model => model.IsExpense, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IsExpense, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsExpense, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsIncome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IsIncome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsIncome, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <br />
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ReconciledAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReconciledAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReconciledAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reconciled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Reconciled)
                    @Html.ValidationMessageFor(model => model.Reconciled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, "Select One", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Budget, "Budget", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudgetId", null, "Select One", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Expense, "Expenses", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExpenseId", null, "Select One", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Expense, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Accounts, "Accounts", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccountsId", null, "Select One", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Accounts, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" style="background-color:orangered;color:white" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

rcate-FinancialPortal/Views/Transactions/Delete.cshtml
@model rcate_FinancialPortal.Models.Code_First.Transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReconciledAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReconciledAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reconciled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reconciled)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

rcate-FinancialPortal/Views/Transactions/Details.cshtml
@model rcate_FinancialPortal.Models.Code_First.Transaction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @string.Format("{0:C}", Model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Model.Created.ToString("d")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReconciledAmount)
        </dt>

        <dd>
            @string.Format("{0:C}", Model.ReconciledAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reconciled)
        </dt>

        <dd>
            @if (Model.Reconciled == true)
            {
                <p>Yes</p>
            }
            else
            {
                <p>No</p>
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

rcate-FinancialPortal/Views/Transactions/Edit.cshtml
@model rcate_FinancialPortal.Models.Code_First.Transaction

@{
    ViewBag.Title = "Edit";
}

<center>
    <h2>
        <b>Edit Transaction</b>
    </h2>
</center>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.AuthorId)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.HouseHoldId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Accounts, "Account", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccountsId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountsId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

rcate-FinancialPortal/Views/Transactions/Index.cshtml
@model IEnumerable<rcate_FinancialPortal.Models.Code_First.Transaction>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Index";
}

<link href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />

<div style="padding-bottom:60px">
    <h2>
        <b>House Transactions</b>
    </h2>

    <p class="pull-right">
        <a class="btn btn-default" style="background-color:orange;color:white" href="@Url.Action("Create", "Transactions")">Create New Transactions</a>
    </p>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <center>
            <h4><b>House Transactions</b></h4>
        </center>
    </div>
    <div class="panel-body">
        @if (Model.Count() == 0)
        {
            <h6><b>You have no transactions.</b></h6>
        }
        else
        {
            <table class="table">
                <tr>
                    <th></th>
                    <th>
                        Owners Name
                    </th>
                    <th>
                        Trans. Name
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Date
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {

                    if (item.Void != true)
                    {
                        <tr>
                            <td></td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Author.FullName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Category.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @string.Format("{0:C}", item.Amount)
                            </td>
                            <td>
                                @item.Created.ToString("d")
                            </td>
                            <td class="pull-right">
                                <a style="color:black" title="Edit" href="@Url.Action("Edit", "Transactions", new { id = item.Id })"><span class="fa fa-pencil"></span></a>
                                &nbsp;
                                <a style="color:black" title="Details" href="@Url.Action("Details", "Transactions", new { id = item.Id })"><span class="fa fa-info-circle"></span></a>
                                &nbsp;
                                <a style="color:red" title="Delete" href="@Url.Action("Delete", "Transactions", new { id = item.Id })"><span class="fa fa-trash-o"></span></a>
                                <br />
                                @using (Html.BeginForm("VoidTransaction", "Transactions", new { id = item.Id }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    <input type="submit" style="color:red;background-color:transparent;border:none" value="VOID" />
                                }
                            </td>
                        </tr>
                    }
                    if (item.Void == true)
                    {
                        <tr style="background-color:whitesmoke;color:red">
                            <td>
                                <p style="color:red">VOIDED</p>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Author.FullName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Category.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @string.Format("{0:C}", item.Amount)
                            </td>
                            <td>
                                @item.Created.ToString("d")
                            </td>
                            <td class="pull-right">
                                <a style="color:black" title="Edit" href="@Url.Action("Edit", "Transactions", new { id = item.Id })"><span class="fa fa-pencil"></span></a>
                                &nbsp;
                                <a style="color:black" title="Details" href="@Url.Action("Details", "Transactions", new { id = item.Id })"><span class="fa fa-info-circle"></span></a>
                                &nbsp;
                                <a style="color:red" title="Delete" href="@Url.Action("Delete", "Transactions", new { id = item.Id })"><span class="fa fa-trash-o"></span></a>
                                <br />
                                @using (Html.BeginForm("UnVoidTransaction", "Transactions", new { id = item.Id }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    <input type="submit" style="color:red;background-color:transparent;border:none" value="Undo Void" />
                                }
                            </td>
                        </tr>
                    }
                }
            </table>

                <hr />
        }

    </div>
    <div class="panel panel-footer"></div>
</div>